[pytest]

testpaths = tests

pythonpath= .

markers =
    ui: Mark tests as UI tests
    api: Mark tests as API tests


addopts =
    --alluredir=reports/allure-results
    --clean-alluredir


console_output_style = progress
