name: QA Automation Suite CI

on:
  push:
    branches: [main, master]
    paths:
      - tests/**
      - core/**
      - utils/**
      - configs/config.json
      - requirements.txt
      - .github/workflows/auto_test.yml
  pull_request:
    branches: [main, master]
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'

env:
  PYTHON_VERSION: "3.11"
  ALLURE_RES_DIR: reports/allure-results
  ALLURE_REPORT_DIR: allure-report

jobs:
  test_task:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browser
        run: |
          python -m playwright install --with-deps chromium

      - name: Install Allure Bin
        run: |
          sudo apt update && sudo apt install -y allure

      - name: Mk report folder
        run: mkdir -p ${{ env.ALLURE_RES_DIR }}

      - name: Run API Test
        run: pytest -m api --alluredir=${{ env.ALLURE_RES_DIR }} --disable-warnings

      - name: Run UI Test
        run: pytest -m ui --alluredir=${{ env.ALLURE_RES_DIR }} --disable-warnings

      - name: Generate Allure Report
        if: always()
        run: allure generate ${{ env.ALLURE_RES_DIR }} -o ${{ env.ALLURE_REPORT_DIR }} --clean

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: ${{ env.ALLURE_REPORT_DIR }}

      - name: Deploy Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.ALLURE_REPORT_DIR }}
          publish_branch: gh-pages